name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 12
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{matrix.node}} on ${{matrix.os}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Installing
        run: npm ci
      - name: Linting scss files
        run: npm run lint

  publish:
    needs: [lint]
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 12
    name: Publishing to npm
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{matrix.node}} on ${{matrix.os}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          registry-url: "https://registry.npmjs.org"
      - name: Installing
        run: npm ci
      - name: Publishing to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
